---
- name: Ensure cUrl is installed.
  win_chocolatey:
     name: curl
     state: present
     
#- name: Ensure Java is installed
#  win_chocolatey:
#     name: jre8
#     state: present
     
- name: Ensure Jenkins is installed.
  win_chocolatey:
     name: jenkins
     state: present
  register: jenkins_install_package_win
